"""Initial revision

Revision ID: 2282f1b2a88c
Revises: 
Create Date: 2026-03-11 15:00:08.125007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2282f1b2a88c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.PrimaryKeyConstraint('discord_id')
    )
    op.create_table('communities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('contact_url', sa.String(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('forward_guild_id', sa.BigInteger(), nullable=True),
    sa.Column('forward_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('admin_role_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['admins.discord_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    
    # Add foreign key constraint from admins to communities after both tables have been created to avoid circular dependency issues
    op.create_foreign_key('admins_community_id_fkey', 'admins', 'communities', ['community_id'], ['id'])

    op.create_index(op.f('ix_communities_forward_guild_id'), 'communities', ['forward_guild_id'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bm_rcon_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('web_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('scopes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('integration_type', sa.Enum('BATTLEMETRICS', 'COMMUNITY_RCON', 'CUSTOM', name='integrationtype'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('api_url', sa.String(), nullable=False),
    sa.Column('banlist_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now() + make_interval(secs=>3600.0)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.discord_id'], ),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_tokens_value'), 'report_tokens', ['value'], unique=True)
    op.create_table('web_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_token', sa.String(), nullable=False),
    sa.Column('scopes', sa.Integer(), nullable=True),
    sa.Column('expires', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['web_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashed_token')
    )
    op.create_table('player_bans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('remote_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'integration_id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reasons_bitflag', sa.Integer(), nullable=False),
    sa.Column('reasons_custom', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('attachment_urls', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['report_tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_messages',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id', 'community_id')
    )
    op.create_index(op.f('ix_report_messages_message_id'), 'report_messages', ['message_id'], unique=True)
    op.create_table('player_report_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('banned', sa.Boolean(), nullable=False),
    sa.Column('reject_reason', sa.Enum('INSUFFICIENT', 'INCONCLUSIVE', name='reportrejectreason'), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['pr_id'], ['player_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pr_id', 'community_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_report_responses')
    op.drop_index(op.f('ix_report_messages_message_id'), table_name='report_messages')
    op.drop_table('report_messages')
    op.drop_table('player_reports')
    op.drop_table('reports')
    op.drop_table('player_bans')
    op.drop_table('web_tokens')
    op.drop_index(op.f('ix_report_tokens_value'), table_name='report_tokens')
    op.drop_table('report_tokens')
    op.drop_table('integrations')
    op.drop_table('web_users')
    op.drop_table('players')
    op.drop_index(op.f('ix_communities_forward_guild_id'), table_name='communities')
    op.drop_table('communities')
    op.drop_table('admins')
    # ### end Alembic commands ###
