"""Add PC Console Fields

Revision ID: 80ff93d59a99
Revises:
Create Date: 2024-08-25 00:04:10.664434

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80ff93d59a99"
down_revision: str | None = "2282f1b2a88c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "communities",
        sa.Column("is_pc", sa.Boolean(), server_default="1", nullable=False),
    )
    op.add_column(
        "communities",
        sa.Column("is_console", sa.Boolean(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("communities", "is_console")
    op.drop_column("communities", "is_pc")
    # ### end Alembic commands ###
