"""Token Platform Field

Revision ID: b343f8659297
Revises: 80ff93d59a99
Create Date: 2024-09-01 14:54:38.648323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b343f8659297'
down_revision: Union[str, None] = '80ff93d59a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_tokens', sa.Column('platform', sa.Enum('PC', 'CONSOLE', name='platform'), server_default='PC', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_tokens', 'platform')
    # ### end Alembic commands ###
