"""Add report filter

Revision ID: b40747208dd2
Revises: b343f8659297
Create Date: 2024-09-05 21:58:47.068979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b40747208dd2'
down_revision: Union[str, None] = 'b343f8659297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('reasons_filter', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('communities', 'reasons_filter')
    # ### end Alembic commands ###
