"""Add Responder Name

Revision ID: 027b31d7016d
Revises: b40747208dd2
Create Date: 2024-09-10 00:48:45.677308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '027b31d7016d'
down_revision: Union[str, None] = 'b40747208dd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_report_responses', sa.Column('responded_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_report_responses', 'responded_by')
    # ### end Alembic commands ###
