"""Add Responder Name

Revision ID: 027b31d7016d
Revises: b40747208dd2
Create Date: 2024-09-10 00:48:45.677308

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "027b31d7016d"
down_revision: str | None = "b40747208dd2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player_report_responses", sa.Column("responded_by", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("player_report_responses", "responded_by")
    # ### end Alembic commands ###
