"""optional owner

Revision ID: b04c97e65cf3
Revises: 266169fb0d75
Create Date: 2024-09-25 16:46:26.649652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b04c97e65cf3'
down_revision: Union[str, None] = '266169fb0d75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('communities', 'owner_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('communities', 'owner_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
