"""Delete integrations

Revision ID: cae0c0791b80
Revises: b04c97e65cf3
Create Date: 2025-02-02 21:24:51.145997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cae0c0791b80'
down_revision: Union[str, None] = 'b04c97e65cf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('player_bans_integration_id_fkey', 'player_bans', type_='foreignkey')
    op.create_foreign_key(None, 'player_bans', 'integrations', ['integration_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player_bans', type_='foreignkey') # type: ignore
    op.create_foreign_key('player_bans_integration_id_fkey', 'player_bans', 'integrations', ['integration_id'], ['id'])
    # ### end Alembic commands ###
