"""Add EOS ID

Revision ID: 75b03de0a5b3
Revises: d8c98d2fef8b
Create Date: 2026-02-07 18:57:17.248536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75b03de0a5b3'
down_revision: Union[str, None] = 'd8c98d2fef8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('eos_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'eos_id')
    # ### end Alembic commands ###
