"""Make token admin optional

Revision ID: c1bb7bf90fb8
Revises: 75b03de0a5b3
Create Date: 2026-04-04 18:44:05.004965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1bb7bf90fb8'
down_revision: Union[str, None] = '75b03de0a5b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report_tokens', 'admin_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report_tokens', 'admin_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
