"""Integration web tokens

Revision ID: 313ff2ffdca8
Revises: 75b03de0a5b3
Create Date: 2026-04-04 23:29:41.296629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '313ff2ffdca8'
down_revision: Union[str, None] = '75b03de0a5b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_tokens', sa.Column('integration_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'web_tokens', ['integration_id'])
    op.create_foreign_key(None, 'web_tokens', 'integrations', ['integration_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'web_tokens', type_='foreignkey') # type: ignore
    op.drop_constraint(None, 'web_tokens', type_='unique') # type: ignore
    op.drop_column('web_tokens', 'integration_id')
    # ### end Alembic commands ###
