"""Community games flag

Revision ID: 56f3f2e67805
Revises: a075bdbccd7e
Create Date: 2026-07-11 16:14:32.200262

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56f3f2e67805"
down_revision: str | None = "a075bdbccd7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "communities", sa.Column("games_bitflag", sa.Integer(), nullable=True)
    )
    op.execute("UPDATE communities SET games_bitflag = 1")
    op.alter_column("communities", "games_bitflag", nullable=False)
    op.drop_column("communities", "is_pc")
    op.drop_column("communities", "is_console")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "communities",
        sa.Column(
            "is_pc",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "communities",
        sa.Column(
            "is_console",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("communities", "games_bitflag")
    # ### end Alembic commands ###
