"""Add report comments

Revision ID: 029504e67ec2
Revises: bc583d539b05
Create Date: 2026-07-18 16:33:57.257790

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "029504e67ec2"
down_revision: str | None = "bc583d539b05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reports", sa.Column("comment", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reports", "comment")
    # ### end Alembic commands ###
